version: "3.8"
services:
  backend:
    image: lms
    restart: always


  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - 5432:5432