service:

  logger:
    cores:
#      - file
      - stdout
    filename: lmg.log
    maxSize: 1024
    maxBackups: 5
    compress: true
    level: debug

  database:
    dbname: postgres
    username: admin
    password: admin
    host: localhost
    port: 5432
    sslmode: disable

  http:
    host: localhost
    port: 5432