name: code check
on: [pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.14.4
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.4
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go mod download
      - name: Lint
        run: diff -u <(echo -n) <(gofmt -l server)